name: Build and push to DockerHub
run-name: Building the image and pushing it to DockerHub.
on:
  push:
    branches: [main]
jobs:
  build_and_push:
    runs-on: ununtu-latest
    steps:
      -
        name: Checkout code.
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ollama-gpu-fix:latest